name: Bug Report
description: I found a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        Please describe the issue with as much detail as possible.
        Explain what happened, and what should have happened instead.
        Add images, screenshots, or videos if they could be useful.
    validations:
      required: true

  - type: input
    attributes:
      label: Crash/error Log
      description: >
        Please provide the crash log or error log. Use https://mclo.gs/ to upload and then provide URL.
    validations:
      required: true
